services:
  - type: web
    name: task-master
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: task-master-data
      mountPath: /data
      sizeGB: 1
